# Generated by Django 3.2.4 on 2021-08-02 19:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210802_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 2, 19, 40, 22, 788607, tzinfo=utc)),
        ),
    ]
